export const widgetRegistry = [
  ["heading", "Heading", "Basic"],
  ["text", "Text Editor", "Basic"],
  ["button", "Button", "Basic"],
  ["image", "Image", "Basic"],
  ["video", "Video", "Basic"],
  ["divider", "Divider", "Basic"],
  ["spacer", "Spacer", "Basic"],
  ["icon", "Icon", "Basic"],
  ["html", "HTML / Code", "Basic"],
  ["icon-box", "Icon Box", "Content"],
  ["image-box", "Image Box", "Content"],
  ["star-rating", "Star Rating", "Content"],
  ["icon-list", "Icon List", "Content"],
  ["counter", "Counter", "Content"],
  ["progress", "Progress Bar", "Content"],
  ["testimonial", "Testimonial", "Content"],
  ["blockquote", "Blockquote", "Content"],
  ["alert", "Alert", "Content"],
  ["gallery", "Gallery", "Media"],
  ["carousel", "Image Carousel", "Media"],
  ["audio", "Audio", "Media"],
  ["map", "Map", "Media"],
  ["tabs", "Tabs", "Interactive"],
  ["accordion", "Accordion", "Interactive"],
  ["toggle", "Toggle", "Interactive"],
  ["social-icons", "Social Icons", "Interactive"],
  ["countdown", "Countdown", "Interactive"],
  ["form", "Form", "Marketing"],
  ["login", "Login", "Marketing"],
  ["search", "Search", "Marketing"],
  ["menu-anchor", "Menu Anchor", "Marketing"],
] as const;
export type WidgetType = (typeof widgetRegistry)[number][0];
export function newWidget(type: WidgetType, id: string) {
  const defaults: Partial<Record<WidgetType, string>> = {
    image: "/api/static/figma/vector1.svg",
    video: "/api/static/video/portfolio.mp4",
    audio: "/api/static/video/portfolio.mp4",
    icon: "★",
    gallery: "/api/static/figma/image213.png\n/figma/image214.png",
    carousel: "/api/static/figma/image213.png\n/figma/image214.png",
    map: "https://www.google.com/maps",
    progress: "75",
    counter: "100",
    ["star-rating"]: "5",
    ["social-icons"]:
      "Instagram|https://instagram.com\nLinkedIn|https://linkedin.com\nFacebook|https://facebook.com",
    accordion: "Question one|Answer one\nQuestion two|Answer two",
    toggle: "Read more|Toggle content",
    tabs: "Tab one|Tab content\nTab two|Second tab content",
    form: "Contact form",
    countdown: "2030-01-01T00:00:00Z",
    testimonial: "A wonderful experience.|Client name",
    blockquote: "A memorable quotation.|Source",
    ["icon-box"]: "★|Icon box title|Supporting description",
    ["image-box"]: "/api/static/figma/image213.png|Image box title|Supporting description",
  };
  return {
    id,
    type,
    content: defaults[type] || `New ${type.replaceAll("-", " ")}`,
    settings: {
      color: "#202126",
      backgroundColor: "transparent",
      fontSize: type === "heading" ? 48 : 16,
      fontWeight: type === "heading" ? 600 : 400,
      align: "center",
      width: 100,
      height: type === "image" || type === "video" ? 320 : 0,
      marginTop: 0,
      marginBottom: 0,
      padding: 0,
      borderWidth: 0,
      borderColor: "transparent",
      borderRadius: 0,
      shadow: "none",
      hoverColor: "#202126",
      hoverBackgroundColor: "transparent",
      animation: "none",
      desktopVisible: true,
      tabletVisible: true,
      mobileVisible: true,
      href: "#",
      alt: "",
      gap: 16,
      columns: 2,
    },
  };
}
