export const widgetRegistry = [
  ["heading", "Heading", "Basic"],
  ["text", "Text Editor", "Basic"],
  ["button", "Button", "Basic"],
  ["image", "Image", "Basic"],
  ["video", "Video", "Basic"],
  ["divider", "Divider", "Basic"],
  ["spacer", "Spacer", "Basic"],
  ["icon", "Icon", "Basic"],
  ["html", "HTML / Code", "Basic"],
  ["icon-box", "Icon Box", "Content"],
  ["image-box", "Image Box", "Content"],
  ["star-rating", "Star Rating", "Content"],
  ["icon-list", "Icon List", "Content"],
  ["counter", "Counter", "Content"],
  ["progress", "Progress Bar", "Content"],
  ["testimonial", "Testimonial", "Content"],
  ["blockquote", "Blockquote", "Content"],
  ["alert", "Alert", "Content"],
  ["gallery", "Gallery", "Media"],
  ["carousel", "Image Carousel", "Media"],
  ["audio", "Audio", "Media"],
  ["map", "Map", "Media"],
  ["tabs", "Tabs", "Interactive"],
  ["accordion", "Accordion", "Interactive"],
  ["toggle", "Toggle", "Interactive"],
  ["social-icons", "Social Icons", "Interactive"],
  ["countdown", "Countdown", "Interactive"],
  ["form", "Form", "Marketing"],
  ["login", "Login", "Marketing"],
  ["search", "Search", "Marketing"],
  ["menu-anchor", "Menu Anchor", "Marketing"],
] as const;
export type WidgetType = (typeof widgetRegistry)[number][0];
export function newWidget(type: WidgetType, id: string) {
  const defaults: Partial<Record<WidgetType, string>> = {
    image: "/figma/vector1.svg",
    video: "/video/portfolio.mp4",
    audio: "/video/portfolio.mp4",
    icon: "★",
    gallery: "/figma/image213.png\n/figma/image214.png",
    carousel: "/figma/image213.png\n/figma/image214.png",
    map: "https://www.google.com/maps",
    progress: "75",
    counter: "100",
    ["star-rating"]: "5",
    ["social-icons"]: "Instagram\nLinkedIn\nFacebook",
    accordion: "Question\nAnswer",
    tabs: "Tab one\nTab content",
    form: "Contact form",
  };
  return {
    id,
    type,
    content: defaults[type] || `New ${type.replaceAll("-", " ")}`,
    settings: {
      color: "#202126",
      fontSize: type === "heading" ? 48 : 16,
      align: "center",
    },
  };
}
